project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    
website:
  title: "filoR"
  sidebar:
    contents:
      - href: index.qmd
        text: Home
      - href: prepa.html
        text: Preparación
      - href: regenta.html
        text: La Regenta
      - href: sombreros.html
        text: Tres sombreros de copa
        
        
format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: source

