project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    
website:
  title: "filoR"
  sidebar:
    contents:
      - href: index.qmd
        text: Introducción al curso
      - href: prepa.html
        text: Preparación
      - href: regenta.html
        text: La Regenta
      - href: sombreros.html
        text: Tres sombreros de copa
  page-footer:
    left: "&copy; Copyright 2024, Rodrigo Rodrigues-Silveira"
        
execute:
  warning: false
  message: false
  error: false

format:
  html:
    theme: pulse
    css: styles.css
    toc: true
    code-fold: show
  

editor: source

