---
title: "<b>filoR</b><br>Análisis de textos literarios con R"
---



## El curso



Esta página web forma parte del curso "Análisis de textos literarios con R". En ella, se recogen los materiales y ejemplos que se desarrollarán durante las sesiones.


## Los profesores


<span style="background-color:purple;color:white;padding:4px;">Rodrigo Rodrigues-Silveira </span> 

[rodrodr@usal.es](mailto:rodrodr@usal.es)

Profesor de ciencia política de la USAL. Director del proyecto "Comportamiento legislativo y erosión democrática en América Latina" (PELA Comportamiento).

<br>

<span style="background-color:green;color:white;padding:4px;">Sheila Pastor</span>

[sheilap@usal.es](mailto:sheilap@usal.es)

Profesora de literatura hispanoamericana de la USAL...

## El contenido

Durante el curso se abordarán los siguientes temas:

- <span style="background: url(https://s2.svgbox.net/pen-brushes.svg?ic=brush-1&color=orange);">preparación de textos literarios</span> para análisis cuantitativos

- análisis de <span style="background: url(https://s2.svgbox.net/pen-brushes.svg?ic=brush-2&color=pink);">frecuencias de palabras</span>

- codificación temática

- análisis de conglomerados <span style="background: url(https://s2.svgbox.net/pen-brushes.svg?ic=brush-3&color=purple);color:white"><b>clusters</b></span>

- escalonado de textos (uni y multidimensional)

- modelage de tópicos

- <span style="background: url(https://s2.svgbox.net/pen-brushes.svg?ic=brush-4&color=skyblue);">análisis de redes</span> sociales

- técnicas de <span style="background: url(https://s2.svgbox.net/pen-brushes.svg?ic=brush-5&color=gold);">visualización de texto</span> 


## Sesiones

Las sesiones tendrán lugar en el etéreo espacio de la nube, en la plataforma Zoom. Los enlaces de acceso a las sesiones se enviarán a los correos electrónicos de los participantes.


<span style="background-color:darkviolet;color:white;padding:4px;">DÍA 1 - 04/05/2024</span> de 10 a 14h


<span style="background-color:seagreen;color:white;padding:4px; ">DÍA 2 - 13/05/2024</span> de 10 a 14h



## `r knitr::asis_output("\U1F916")` Servicio técnico `r knitr::asis_output("\U1F916")`	

Para que podáis reproducir los ejemplos de análisis presentados durante el curso debéis instalar en vuestros ordenadores el [R](https://cran.r-project.org/) y el [RStudio Desktop](https://posit.co/downloads/).

También debéis ejecutar el siguiente código en R que instala los paquetes necesarios:

```{r, eval=F}

# Crea un vector con los paquetes a instalar
pc <- c("quanteda","quanteda.textplots",
        "quanteda.textmodels","quanteda.textstats",
        "stringi","readr","gutenbergr","ggplot2",
        "ggrepel","reactable","tidyverse","devtools",
        "egg","network","sna","ggnetwork")

# Instala los paquetes
install.packages(pc)

# Instala el paquete tenet que no está en CRAN
devtools::install_github("rodrodr/tenet", force=T)

```

